fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: black
        entry: poetry run black --check .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort --check-only .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: pylint
        entry: poetry run pylint -j 0 arango_wal
        pass_filenames: false
        language: system
